// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqzaDrlG-3WvvXl86ViYDU3RZwRfw_b70',
    appId: '1:722238457549:web:1cb0208f15b77b2db28b84',
    messagingSenderId: '722238457549',
    projectId: 'cuidapp-proyecto',
    authDomain: 'cuidapp-proyecto.firebaseapp.com',
    storageBucket: 'cuidapp-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhMk0OpocqHOloVOAfHqTLo4pOLoANCs',
    appId: '1:722238457549:android:79858f4bdcac0554b28b84',
    messagingSenderId: '722238457549',
    projectId: 'cuidapp-proyecto',
    storageBucket: 'cuidapp-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMbkU3wYc7CDiAyns7ZNVTlnaOXDEUBY',
    appId: '1:722238457549:ios:70742ebbe03ffac9b28b84',
    messagingSenderId: '722238457549',
    projectId: 'cuidapp-proyecto',
    storageBucket: 'cuidapp-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.cuidapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwMbkU3wYc7CDiAyns7ZNVTlnaOXDEUBY',
    appId: '1:722238457549:ios:70742ebbe03ffac9b28b84',
    messagingSenderId: '722238457549',
    projectId: 'cuidapp-proyecto',
    storageBucket: 'cuidapp-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.cuidapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqzaDrlG-3WvvXl86ViYDU3RZwRfw_b70',
    appId: '1:722238457549:web:fd0cd40d96c2aae9b28b84',
    messagingSenderId: '722238457549',
    projectId: 'cuidapp-proyecto',
    authDomain: 'cuidapp-proyecto.firebaseapp.com',
    storageBucket: 'cuidapp-proyecto.firebasestorage.app',
  );
}